### ISSUE TITLE
How to get the attack examples with SaliencyMapMethod on the ImageNet datasets?

### ISSUE THREAD

**Issue by shenqixiaojiang** [tensorflow/cleverhans#247]
Here, I want to get the attack examples with SaliencyMapMethod on the ImageNet datasets based on the examples/nips17_adversarial_competition/sample_attacks/fgsm/attack_fgsm.py file.

And I just change the following code :

```
   fgsm = FastGradientMethod(model)
   x_adv = fgsm.generate(x_input, eps=eps, clip_min=-1., clip_max=1.)
```
with:

```
    jsma= SaliencyMapMethod(model)
    target = np.zeros((1,1000),dtype=np.float32)
    target[0,50] = 1                    #here, we suppose that the target label is 50
    jsma_params = {'theta': 1., 'gamma': 0.1,
                   'clip_min': 0., 'clip_max': 1.,
                   'y_target': target}
    x_adv = jsma.generate(x_input,**jsma_params)
```
But, it doesn't work.

**Comment by npapernot** [comment]
Could you tell us what the error is?

**Comment by shenqixiaojiang** [comment]
@npapernot The error "UnknownError (see above for traceback): exceptions.AttributeError: 'NoneType' object has no attribute 'run'" is reported.

**Comment by npapernot** [comment]
Off the top of my head, it seems like the session is not passed properly? That would be the sess.run call. It's hard to say anything more with what you shared. Feel free to reopen with more details.

**Comment by ajing** [comment]
I experienced some similar errors:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/attacks.py", line 364, in jsma_wrap
    targets=None)
  File "/usr/local/lib/python2.7/dist-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/attacks_tf.py", line 355, in jsma_batch
    gt = model_argmax(sess, x, pred, val)
  File "/usr/local/lib/python2.7/dist-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/utils_tf.py", line 334, in model_argmax
    probabilities = sess.run(predictions, feed_dict)
AttributeError: 'NoneType' object has no attribute 'run'
2017-09-07 18:42:19.049038: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_0: see error log.
Traceback (most recent call last):
  File "attack_salmap.py", line 151, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "attack_salmap.py", line 146, in main
    adv_images = sess.run(x_adv, feed_dict={x_input: images})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 484, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 820, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 776, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 930, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 776, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_0: see error log.
         [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_0)]]

Caused by op u'PyFunc', defined at:
  File "attack_salmap.py", line 151, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "attack_salmap.py", line 135, in main
    x_adv = fgsm.generate(x_input, clip_min=-1., clip_max=1.)
  File "/usr/local/lib/python2.7/dist-packages/cleverhans-1.0.0-py2.7.egg/cleverhans/attacks.py", line 367, in generate
    wrap = tf.py_func(jsma_wrap, [x], tf.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_0: see error log.
         [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_0)]]
```

The code is like this:

```
  eps = 2.0 * FLAGS.max_epsilon / 255.0
  batch_shape = [FLAGS.batch_size, FLAGS.image_height, FLAGS.image_width, 3]
  num_classes = 1001

  tf.logging.set_verbosity(tf.logging.INFO)

  with tf.Graph().as_default():
    # Prepare graph
    x_input = tf.placeholder(tf.float32, shape=batch_shape)

    model = InceptionModel(num_classes)

    salmap= SaliencyMapMethod(model)
    x_adv = salmap.generate(x_input, clip_min=-1., clip_max=1.)

    # Run computation
    saver = tf.train.Saver(slim.get_model_variables())
    session_creator = tf.train.ChiefSessionCreator(
        scaffold=tf.train.Scaffold(saver=saver),
        checkpoint_filename_with_path=FLAGS.checkpoint_path,
        master=FLAGS.master)

    with tf.train.MonitoredSession(session_creator=session_creator) as sess:
      for filenames, images in load_images(FLAGS.input_dir, batch_shape):
        adv_images = sess.run(x_adv, feed_dict={x_input: images})
        save_images(adv_images, filenames, FLAGS.output_dir)
```

**Comment by npapernot** [comment]
Thanks for letting us know. Can you try to update to the last version, there has been changes to these functions since then. From the log, it seems that you are using 1.0

**Comment by ajing** [comment]
Thanks for the quick response and suggestion!

After updating cleverhans to 2.0. The error is like this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/root/src/cleverhans/cleverhans/attacks.py", line 534, in jsma_wrap
    y_target=None)
  File "/root/src/cleverhans/cleverhans/attacks_tf.py", line 393, in jsma_batch
    gt = model_argmax(sess, x, pred, val, feed=feed)
  File "/root/src/cleverhans/cleverhans/utils_tf.py", line 377, in model_argmax
    probabilities = sess.run(predictions, feed_dict)
AttributeError: 'NoneType' object has no attribute 'run'
2017-09-09 02:02:38.473482: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_0: see error log.
Traceback (most recent call last):
  File "attack_salmap.py", line 151, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "attack_salmap.py", line 146, in main
    adv_images = sess.run(x_adv, feed_dict={x_input: images})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 484, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 820, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 776, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 930, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 776, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_0: see error log.
         [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_0)]]
 
Caused by op u'PyFunc', defined at:
  File "attack_salmap.py", line 151, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "attack_salmap.py", line 135, in main
    x_adv = fgsm.generate(x_input, clip_min=-1., clip_max=1.)
  File "/root/src/cleverhans/cleverhans/attacks.py", line 537, in generate
    wrap = tf.py_func(jsma_wrap, [x], tf.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()
 
InternalError (see above for traceback): Failed to run py callback pyfunc_0: see error log.
         [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_0)]]
 
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 1439, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 1386, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/ubuntu/cleverhans/examples/nips17_adversarial_competition/run_attacks_and_defenses.py", line 557, in <module>
    main()
  File "/home/ubuntu/cleverhans/examples/nips17_adversarial_competition/run_attacks_and_defenses.py", line 531, in main
    args.epsilon)
  File "/home/ubuntu/cleverhans/examples/nips17_adversarial_competition/run_attacks_and_defenses.py", line 98, in run
    subprocess.call(cmd)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 271, in call
    p.kill()
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 1572, in kill
    self.send_signal(signal.SIGKILL)
  File "/home/ubuntu/anaconda3/lib/python3.6/subprocess.py", line 1562, in send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted

```

**Comment by npapernot** [comment]
Have you tried running something in that session before this line of code gets executed? 

Do you get the same error if you try to use the function `jsma` in `attacks_tf.py` directly (instead of going through the class in `attacks.py`.

**Comment by ajing** [comment]
I think the reason may be when I create the SaliencyMapMethod object, I also need to pass the session object. But, I am not sure how to create a graph after creating a session.

Here is what I try:

```
def main(_):
  # Images for inception classifier are normalized to be in [-1, 1] interval,
  # eps is a difference between pixels so it should be in [0, 2] interval.
  # Renormalizing epsilon from [0, 255] to [0, 2].
  eps = 2.0 * FLAGS.max_epsilon / 255.0
  batch_shape = [FLAGS.batch_size, FLAGS.image_height, FLAGS.image_width, 3]
  num_classes = 1001

  from cleverhans.attacks_tf import jacobian_graph, jsma_batch

  tf.logging.set_verbosity(tf.logging.INFO)

  with tf.Graph().as_default():
    # Prepare graph
    x_input = tf.placeholder(tf.float32, shape=batch_shape)

    model = InceptionModel(num_classes)

    preds = model(x_input)
    grads = jacobian_graph(preds, x_input, num_classes)

    # Run computation
    saver = tf.train.Saver(slim.get_model_variables())
    session_creator = tf.train.ChiefSessionCreator(
        scaffold=tf.train.Scaffold(saver=saver),
        checkpoint_filename_with_path=FLAGS.checkpoint_path,
        master=FLAGS.master)

    with tf.train.MonitoredSession(session_creator=session_creator) as sess:
      print("Session is closed:",sess._is_closed())

      def jsma_wrap(x_val):
          jsma_batch(sess, x, preds, grads, x_val,
                                    1, 0.1, -1,
                                    1, num_classes,
                                    y_target=None)
      x_adv = tf.py_func(jsma_wrap, [x_input], tf.float32)


      for filenames, images in load_images(FLAGS.input_dir, batch_shape):
        adv_images = sess.run(x_adv, feed_dict={x_input: images})
        save_images(adv_images, filenames, FLAGS.output_dir)

```

The output:

```
Session is closed: False
Traceback (most recent call last):
  File "attack_salmap_dev.py", line 163, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "attack_salmap_dev.py", line 154, in main
    x_adv = tf.py_func(jsma_wrap, [x_input], tf.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2288, in create_op
    self._check_not_finalized()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2011, in _check_not_finalized
    raise RuntimeError("Graph is finalized and cannot be modified.")
RuntimeError: Graph is finalized and cannot be modified.
```

**Comment by npapernot** [comment]
It looks like you are defining the jacobian graph before creating your session, this may be the problem.

Otherwise, did you make sure that your function InceptionModel returns the right type of tensor when it is called on an input?

**Comment by XiminLin** [comment]
I experience the similar problems here. I was trying to merge CarliniWagnerL2 attack in attacks.py into examples/nips17_adversarial_competition/sample_attacks.

I got the error when I keep the SessionMonitor() the same as attack_fgsm.py. However, I was getting error like uninitialized variables... Like Below

    INFO:tensorflow:Restoring parameters from inception_v3.ckpt
      INFO:tensorflow:Restoring parameters from inception_v3.ckpt
      Traceback (most recent call last):
        File "attack_cwL2.py", line 217, in <module>
          tf.app.run()
        File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
          _sys.exit(main(_sys.argv[:1] + flags_passthrough))
        File "attack_cwL2.py", line 202, in main
          with tf.train.MonitoredSession(session_creator=session_creator) as sess:
        File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 668, in __init__
          stop_grace_period_secs=stop_grace_period_secs)
        File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 490, in __init__
          self._sess = _RecoverableSession(self._coordinated_creator)
        File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 842, in __init__
          _WrappedSession.__init__(self, self._create_session())
        File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 847, in _create_session
          return self._sess_creator.create_session()
        File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 551, in create_session
          self.tf_sess = self._session_creator.create_session()
        File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 425, in create_session
          init_fn=self._scaffold.init_fn)
        File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/session_manager.py", line 289, in prepare_session
          msg))
      RuntimeError: Init operations did not make model ready for local_init.  Init op: group_deps, init fn: None, error: Variables not initialized: Variable, timg, tlab, const, beta1_power, beta2_power, Variable/Adam, Variable/Adam_1


After some searchings in the web, one possible answer is that the program tried to run two tensorflow at the same time. Then I thought maybe tensorflow does not connect the graph defined for inception model and the graph of attacks inside CarliniWagnerL2 attacks. 

Then I changed the code to better resemble the mnist_tutorial_cw.py, which runs CarliniWagnerL2 attacks in mnist dataset instead. The code is below:

    eps = 2.0 * FLAGS.max_epsilon / 255.0
    batch_shape = [FLAGS.batch_size, FLAGS.image_height, FLAGS.image_width, 3]
    num_classes = 1001

    tf.logging.set_verbosity(tf.logging.INFO)

    with tf.Graph().as_default():
      # Prepare graph
      x_input = tf.placeholder(tf.float32, shape=batch_shape)

      model = InceptionModel(num_classes)

      cw = CarliniWagnerL2(model)

      # untargetted attacks
      cw_params = {
                # "batch_size": FLAGS.batch_size,
                "clip_min": -1.0,
                "clip_max": 1.0,
                # 'binary_search_steps': 1,
                }

      x_adv = cw.generate(x_input, **cw_params)

      sess = tf.Session()

      # Run computation
      saver = tf.train.Saver(slim.get_model_variables())

      ckpt = tf.train.get_checkpoint_state(FLAGS.checkpoint_path)
      if ckpt and ckpt.model_checkpoint_path:
        saver.restore(sess, ckpt.model_checkpoint_path)

        
        
      sess.run(tf.global_variables_initializer() )
      for filenames, images in load_images(FLAGS.input_dir, batch_shape):
        adv_images = sess.run(x_adv, feed_dict={x_input: images})
        save_images(adv_images, filenames, FLAGS.output_dir)

So I restore the model explicitly myself and try to run the entire thing with sess. But I got another error below:


    2017-09-14 22:07:53.570776: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: AttributeError: 'NoneType' object has no attribute 'run'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
        return fn(*args)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
        status, run_metadata)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
        next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
        pywrap_tensorflow.TF_GetCode(status))
    tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'NoneType' object has no attribute 'run'
    	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_Placeholder_0_0, _arg_Placeholder_1_0_1)]]

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "attack_cwL2.py", line 217, in <module>
        tf.app.run()
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
        _sys.exit(main(_sys.argv[:1] + flags_passthrough))
      File "attack_cwL2.py", line 213, in main
        adv_images = sess.run(x_adv, feed_dict={x_input: images, y_input: reals})
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
        run_metadata_ptr)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
        feed_dict_tensor, options, run_metadata)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
        options, run_metadata)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'NoneType' object has no attribute 'run'
    	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_Placeholder_0_0, _arg_Placeholder_1_0_1)]]

    Caused by op 'PyFunc', defined at:
      File "attack_cwL2.py", line 217, in <module>
        tf.app.run()
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
        _sys.exit(main(_sys.argv[:1] + flags_passthrough))
      File "attack_cwL2.py", line 184, in main
        x_adv = cw.generate(x_input, **cw_params)
      File "/Users/ximinlin/Documents/Python/malwares/cleverhans/cleverhans/attacks.py", line 726, in generate
        wrap = tf.py_func(cw_wrap, [x, labels], tf.float32)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 203, in py_func
        input=inp, token=token, Tout=Tout, name=name)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 36, in _py_func
        name=name)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
        op_def=op_def)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
        original_op=self._default_original_op, op_def=op_def)
      File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
        self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

    UnknownError (see above for traceback): AttributeError: 'NoneType' object has no attribute 'run'
    	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_Placeholder_0_0, _arg_Placeholder_1_0_1)]] 

I think the Nonetype is referring to sess, since I am not calling any run() in my code. So I later print out the sess.

    <tensorflow.python.client.session.Session object at 0x11c653ba8>

which is definitely not None....

**Comment by rwightman** [comment]
@XiminLin: The .sess member of the Attack class is None, not your own. You need to create the session and pass it to the attack class as in the test_attack, TestCarliniWagnerL2 or the MINST examples...

**Comment by ajing** [comment]
@npapernot @XiminLin 

I think I solve this problem by:

1. use tf.Session() instead of tf.train.MonitoredSession()
2. pass session variable when initializing the attack

But the gradient graph calculation seems to take quite some time. I am considering saving it as a graph and load the graph from the file. 

Thanks for helping!

**Comment by XiminLin** [comment]
Seems that it solves my problems as well. But it takes too long to run... Thanks for helping

**Comment by ariewahyu** [comment]
I still got the same error as @XiminLin 
Can you show your working code?
